import { useMemo, useState } from 'react';
import { mockUsers, type AdminUserRecord } from '../../../mocks/users';
import { formatDateTime } from '../../../utils/formatDate';
import { roleLabel } from '../../../store/authStore';

export default function AdminUsersPage() {
  const [users, setUsers] = useState<AdminUserRecord[]>(mockUsers); const [search, setSearch] = useState(''); const [role, setRole] = useState('ALL');
  const filtered = useMemo(() => users.filter((user) => (role === 'ALL' || user.role === role) && `${user.fullName} ${user.email}`.toLowerCase().includes(search.toLowerCase())), [users, search, role]);
  const toggle = (id: string) => setUsers((items) => items.map((user) => user.id === id && user.role !== 'ADMIN' ? { ...user, status: user.status === 'ACTIVE' ? 'INACTIVE' : 'ACTIVE' } : user));
  return <div className="mx-auto max-w-7xl px-6 py-10 sm:py-14"><span className="font-mono-tag text-xs uppercase tracking-[0.2em] text-[var(--color-primary)]">Admin · Người dùng</span><h1 className="mt-2 font-display text-4xl">Quản lý tài khoản</h1><div className="mt-7 grid gap-3 sm:grid-cols-[1fr_220px]"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Tìm theo tên hoặc email..." className="rounded-lg border border-[var(--color-border)] bg-[var(--color-surface)] px-4 py-3 text-sm outline-none focus:border-[var(--color-primary)]" /><select value={role} onChange={(event) => setRole(event.target.value)} className="rounded-lg border border-[var(--color-border)] bg-[var(--color-surface)] px-4 py-3 text-sm"><option value="ALL">Tất cả vai trò</option><option value="USER">Thành viên</option><option value="ADMIN">Admin</option></select></div><div className="mt-5 overflow-x-auto rounded-xl border border-[var(--color-border)] bg-[var(--color-surface)]"><table className="w-full min-w-[800px] text-left"><thead className="border-b border-[var(--color-border)] text-[10px] uppercase tracking-wider text-[var(--color-text-dim)]"><tr><th className="p-4">Người dùng</th><th>Vai trò</th><th>Tham gia</th><th>Hoạt động</th><th>Trạng thái</th><th className="pr-4 text-right">Thao tác</th></tr></thead><tbody className="divide-y divide-[var(--color-border)]">{filtered.map((user) => <tr key={user.id}><td className="p-4"><p className="text-sm text-[var(--color-text)]">{user.fullName}</p><p className="mt-1 text-xs text-[var(--color-text-dim)]">{user.email}</p></td><td><span className="rounded-full border border-[var(--color-primary)]/30 px-2.5 py-1 text-[10px] text-[var(--color-primary)]">{roleLabel[user.role]}</span></td><td className="text-xs text-[var(--color-text-muted)]">{formatDateTime(user.joinedAt)}</td><td className="text-xs text-[var(--color-text-muted)]">{user.auctions} phiên · {user.bids} lượt bid</td><td><span className={`text-xs ${user.status === 'ACTIVE' ? 'text-[var(--color-success)]' : 'text-[var(--color-danger)]'}`}>{user.status}</span></td><td className="pr-4 text-right"><button disabled={user.role === 'ADMIN'} onClick={() => toggle(user.id)} className="rounded-md border border-[var(--color-border-strong)] px-3 py-1.5 text-xs text-[var(--color-text)] disabled:opacity-30">{user.status === 'ACTIVE' ? 'Khóa' : 'Mở khóa'}</button></td></tr>)}</tbody></table></div></div>;
}
