import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { mockAuctions } from '../../../mocks/auctions';
import type { Auction, AuctionStatus } from '../../auction/types';
import { auctionStatusLabel, auctionStatusTone } from '../../../constants/auctionStatus';
import { formatCurrency } from '../../../utils/formatCurrency';

export default function AdminAuctionsPage() {
  const [items, setItems] = useState<Auction[]>(mockAuctions); const [filter, setFilter] = useState<AuctionStatus | 'ALL'>('ALL');
  const visible = useMemo(() => items.filter((item) => filter === 'ALL' || item.status === filter), [items, filter]);
  const setStatus = (id: number, status: AuctionStatus) => setItems((current) => current.map((item) => item.id === id ? { ...item, status } : item));
  return <div className="mx-auto max-w-7xl px-6 py-10 sm:py-14"><span className="font-mono-tag text-xs uppercase tracking-[0.2em] text-[#C9A227]">Admin · Kiểm duyệt</span><h1 className="mt-2 font-display text-4xl">Quản lý phiên đấu giá</h1><p className="mt-2 text-sm text-[#7d9186]">Duyệt, hủy hoặc mở lại phiên trong dữ liệu demo.</p><div className="mt-7 flex gap-2 overflow-x-auto">{(['ALL', 'UPCOMING', 'ACTIVE', 'ENDED', 'CANCELLED'] as const).map((status) => <button key={status} onClick={() => setFilter(status)} className={`rounded-full border px-4 py-2 text-xs ${filter === status ? 'border-[#C9A227] bg-[#C9A227] text-[#0F1B14]' : 'border-[#3a4d40] text-[#7d9186]'}`}>{status === 'ALL' ? 'Tất cả' : auctionStatusLabel[status]}</button>)}</div><div className="mt-5 space-y-4">{visible.map((auction) => <article key={auction.id} className="grid gap-4 rounded-xl border border-[#2a3f31] bg-[#14231a] p-4 md:grid-cols-[100px_1fr_auto] md:items-center"><img src={auction.image} alt="" className="h-20 w-full rounded-lg object-cover md:w-24" /><div><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full border px-2.5 py-1 text-[10px] ${auctionStatusTone[auction.status]}`}>{auctionStatusLabel[auction.status]}</span><span className="text-xs text-[#607468]">Seller: {auction.seller}</span></div><h2 className="mt-2 font-display text-lg">{auction.title}</h2><p className="mt-2 text-xs text-[#7d9186]">{formatCurrency(auction.currentPrice)} · {auction.bidCount} lượt bid · {auction.category}</p></div><div className="flex flex-wrap gap-2 md:max-w-56 md:justify-end"><Link to={`/auctions/${auction.id}`} className="rounded-md border border-[#3a4d40] px-3 py-2 text-xs">Chi tiết</Link>{auction.status === 'UPCOMING' && <button onClick={() => setStatus(auction.id, 'ACTIVE')} className="rounded-md bg-[#C9A227] px-3 py-2 text-xs font-semibold text-[#0F1B14]">Duyệt</button>}{auction.status !== 'ENDED' && auction.status !== 'CANCELLED' && <button onClick={() => setStatus(auction.id, 'CANCELLED')} className="rounded-md border border-[#C2452D]/50 px-3 py-2 text-xs text-[#ff9a86]">Hủy</button>}{auction.status === 'CANCELLED' && <button onClick={() => setStatus(auction.id, 'UPCOMING')} className="rounded-md border border-[#4e8b5e]/50 px-3 py-2 text-xs text-[#8fc99c]">Mở lại</button>}</div></article>)}</div></div>;
}
