import { useState } from 'react';
import { Link } from 'react-router-dom';
import Button from '../../../components/common/Button';
import { formatCurrency } from '../../../utils/formatCurrency';

export default function DepositPage() {
  const [amount, setAmount] = useState(5_000_000); const [loading, setLoading] = useState(false); const [message, setMessage] = useState('');
  const submit = (event: React.FormEvent) => { event.preventDefault(); setMessage(''); if (!Number.isFinite(amount) || amount <= 0) return setMessage('Số tiền phải lớn hơn 0.'); setLoading(true); window.setTimeout(() => { setLoading(false); setMessage(`Nạp tiền demo thành công. Số dư mới: ${formatCurrency(50_000_000 + amount)}.`); }, 600); };
  return <div className="mx-auto max-w-3xl px-6 py-10 sm:py-14"><Link to="/wallet" className="text-sm text-[#7d9186] hover:text-[#C9A227]">← Quay lại ví</Link><div className="mt-7"><span className="font-mono-tag text-xs uppercase tracking-[0.2em] text-[#C9A227]">UC08 · Nạp tiền</span><h1 className="mt-2 font-display text-4xl">Bổ sung số dư</h1><p className="mt-2 text-sm text-[#7d9186]">Giao dịch mô phỏng, không phát sinh thanh toán thật.</p></div><div className="mt-7 grid grid-cols-3 gap-3">{[['Tổng số dư', 50_000_000], ['Khả dụng', 37_000_000], ['Đang khóa', 13_000_000]].map(([label, value]) => <div key={label} className="rounded-xl border border-[#2a3f31] bg-[#14231a] p-4"><p className="text-[10px] uppercase text-[#607468]">{label}</p><p className="mt-2 font-display text-lg text-[#F3EFE6]">{formatCurrency(Number(value))}</p></div>)}</div><form onSubmit={submit} className="mt-6 rounded-2xl border border-[#2a3f31] bg-[#14231a] p-6 sm:p-8"><label className="text-xs uppercase tracking-wider text-[#7d9186]">Số tiền muốn nạp</label><div className="mt-2 flex overflow-hidden rounded-lg border border-[#3a4d40] focus-within:border-[#C9A227]"><input type="number" min="1" value={amount} onChange={(event) => setAmount(Number(event.target.value))} className="min-w-0 flex-1 bg-[#0F1B14] px-4 py-4 font-display text-2xl text-[#F3EFE6] outline-none" /><span className="flex items-center border-l border-[#3a4d40] bg-[#1d2d23] px-5 text-sm text-[#7d9186]">VND</span></div><div className="mt-3 grid grid-cols-3 gap-2">{[1_000_000, 5_000_000, 10_000_000].map((value) => <button type="button" key={value} onClick={() => setAmount(value)} className={`rounded-md border px-2 py-2.5 text-xs ${amount === value ? 'border-[#C9A227] text-[#C9A227]' : 'border-[#2a3f31] text-[#7d9186]'}`}>{formatCurrency(value)}</button>)}</div><Button type="submit" disabled={loading} className="mt-6 w-full">{loading ? 'Đang xử lý...' : 'Nạp tiền'}</Button>{message && <p className={`mt-4 text-center text-sm ${message.startsWith('Nạp') ? 'text-[#8fc99c]' : 'text-[#ff9a86]'}`}>{message}</p>}</form></div>;
}
