import { useState } from 'react';
import { Link } from 'react-router-dom';
import Button from '../../../components/common/Button';
import { formatCurrency } from '../../../utils/formatCurrency';

export default function DepositPage() {
  const [amount, setAmount] = useState(5_000_000); const [loading, setLoading] = useState(false); const [message, setMessage] = useState('');
  const submit = (event: React.FormEvent) => { event.preventDefault(); setMessage(''); if (!Number.isFinite(amount) || amount <= 0) return setMessage('Số tiền phải lớn hơn 0.'); setLoading(true); window.setTimeout(() => { setLoading(false); setMessage(`Nạp tiền demo thành công. Số dư mới: ${formatCurrency(50_000_000 + amount)}.`); }, 600); };
  return <div className="mx-auto max-w-3xl px-6 py-10 sm:py-14"><Link to="/wallet" className="text-sm text-[var(--color-text-muted)] hover:text-[var(--color-primary)]">← Quay lại ví</Link><div className="mt-7"><span className="font-mono-tag text-xs uppercase tracking-[0.2em] text-[var(--color-primary)]">UC08 · Nạp tiền</span><h1 className="mt-2 font-display text-4xl">Bổ sung số dư</h1><p className="mt-2 text-sm text-[var(--color-text-muted)]">Giao dịch mô phỏng, không phát sinh thanh toán thật.</p></div><div className="mt-7 grid grid-cols-3 gap-3">{[['Tổng số dư', 50_000_000], ['Khả dụng', 37_000_000], ['Đang khóa', 13_000_000]].map(([label, value]) => <div key={label} className="rounded-xl border border-[var(--color-border)] bg-[var(--color-surface)] p-4"><p className="text-[10px] uppercase text-[var(--color-text-dim)]">{label}</p><p className="mt-2 font-display text-lg text-[var(--color-text)]">{formatCurrency(Number(value))}</p></div>)}</div><form onSubmit={submit} className="mt-6 rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)] p-6 sm:p-8"><label className="text-xs uppercase tracking-wider text-[var(--color-text-muted)]">Số tiền muốn nạp</label><div className="mt-2 flex overflow-hidden rounded-lg border border-[var(--color-border-strong)] focus-within:border-[var(--color-primary)]"><input type="number" min="1" value={amount} onChange={(event) => setAmount(Number(event.target.value))} className="min-w-0 flex-1 bg-[var(--color-bg)] px-4 py-4 font-display text-2xl text-[var(--color-text)] outline-none" /><span className="flex items-center border-l border-[var(--color-border-strong)] bg-[var(--color-surface-raised)] px-5 text-sm text-[var(--color-text-muted)]">VND</span></div><div className="mt-3 grid grid-cols-3 gap-2">{[1_000_000, 5_000_000, 10_000_000].map((value) => <button type="button" key={value} onClick={() => setAmount(value)} className={`rounded-md border px-2 py-2.5 text-xs ${amount === value ? 'border-[var(--color-primary)] text-[var(--color-primary)]' : 'border-[var(--color-border)] text-[var(--color-text-muted)]'}`}>{formatCurrency(value)}</button>)}</div><Button type="submit" disabled={loading} className="mt-6 w-full">{loading ? 'Đang xử lý...' : 'Nạp tiền'}</Button>{message && <p className={`mt-4 text-center text-sm ${message.startsWith('Nạp') ? 'text-[var(--color-success)]' : 'text-[var(--color-danger)]'}`}>{message}</p>}</form></div>;
}
