from typing import Protocol, runtime_checkable


@runtime_checkable
class RealtimeConnection(Protocol):
    async def accept(self) -> None: ...

    async def send_json(self, data: dict) -> None: ...

    async def receive_text(self) -> str: ...

    async def close(self, code: int = 1000) -> None: ...
